services:
  - type: web
    name: any-to-pdf-backend
    env: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libreoffice
      npm install
    startCommand: npm start
